<%@ Page Language="C#" AutoEventWireup="true" CodeFile="GridViewDemo.aspx.cs" Inherits="GridViewDemo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 37%;
        }
        .auto-style2 {}
        .auto-style3 {
            width: 16%;
        }
        .auto-style4 {
            width: 61px;
        }
        .auto-style5 {
            width: 15%;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Ecode" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" Height="302px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="424px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="Ecode" HeaderText="Ecode" ReadOnly="True" SortExpression="Ecode" />
                <asp:BoundField DataField="Ename" HeaderText="Ename" SortExpression="Ename" />
                <asp:BoundField DataField="salary" HeaderText="salary" SortExpression="salary" />
                <asp:BoundField DataField="deptid" HeaderText="deptid" SortExpression="deptid" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ValtechDBConnectionString %>" DeleteCommand="DELETE FROM [tbl_employee] WHERE [Ecode] = @Ecode" InsertCommand="INSERT INTO [tbl_employee] ([Ecode], [Ename], [salary], [deptid]) VALUES (@Ecode, @Ename, @salary, @deptid)" SelectCommand="SELECT * FROM [tbl_employee]" UpdateCommand="UPDATE [tbl_employee] SET [Ename] = @Ename, [salary] = @salary, [deptid] = @deptid WHERE [Ecode] = @Ecode">
            <DeleteParameters>
                <asp:Parameter Name="Ecode" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:ControlParameter ControlID="txtecode" Name="Ecode" PropertyName="Text" Type="Int32" />
                <asp:ControlParameter ControlID="txtename" Name="Ename" PropertyName="Text" Type="String" />
                <asp:ControlParameter ControlID="txtsalary" Name="salary" PropertyName="Text" Type="Int32" />
                <asp:ControlParameter ControlID="txtdeptid" Name="deptid" PropertyName="Text" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Ename" Type="String" />
                <asp:Parameter Name="salary" Type="Int32" />
                <asp:Parameter Name="deptid" Type="Int32" />
                <asp:Parameter Name="Ecode" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    <div>
    
    </div>
    <div>
    
    </div>
        <table style="width: 60%; height: 120px; border:solid 2px black; padding:5px;">
            <tr>
                <td colspan="2">
                    <asp:Label ID="Label2" runat="server" BackColor="#FFFF99" Font-Italic="True" Font-Size="Medium" Text="EMPLOYEE FORM"></asp:Label>
                </td>
            </tr>
            <tr>
                <td>Ecode:</td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtecode" runat="server" BorderStyle="Solid"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>Ename:</td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtename" runat="server" BorderStyle="Solid"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>Salary:</td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtsalary" runat="server" BorderStyle="Solid"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>Deptid:</td>
                <td class="auto-style1">
                    <asp:TextBox ID="txtdeptid" runat="server" BorderStyle="Solid"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">
                    <asp:Button ID="btninsert" runat="server" Text="Insert" OnClick="btninsert_Click" />
                </td>
                <td class="auto-style1">
                    <asp:Label ID="lblMsg" runat="server" Text="Label"></asp:Label>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
